"""Generate LaTeX tables and macros for the supplementary material (no hand-typed numbers).
Output: 06_paper/en_supp/supp_numbers.tex, supp_simtable.tex
"""
import importlib.util
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
RES = ROOT / "02_実験" / "results"
OUT = ROOT / "06_paper" / "en_supp"
OUT.mkdir(parents=True, exist_ok=True)
_s = importlib.util.spec_from_file_location("its", HERE / "04_its.py"); its = importlib.util.module_from_spec(_s); _s.loader.exec_module(its)


def main() -> None:
    par = pd.read_csv(RES / "simulation_params.csv").set_index("which")
    m = {}
    for w, W in [("control", "C"), ("gap", "G")]:
        for k, K in [("s_irr", "Irr"), ("s_lvl", "Lvl"), ("s_ar", "Ar"), ("phi", "Phi"), ("mean", "Mean")]:
            m[f"sim{W}{K}"] = f"{par.loc[w, k] * (100 if k != 'phi' else 1):.4f}"
    t = np.arange(138, dtype=float)
    kn = np.quantile(t[t < its.T0], [0.05, 0.35, 0.65, 0.95])
    m["simKnots"] = ", ".join(f"{k:.1f}" for k in kn)
    m["simT"], m["simTzero"] = "138", str(its.T0)
    m["simPlaceboN"] = str(len(list(its.PLACEBO_T0)))
    lines = [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in m.items()]
    (OUT / "supp_numbers.tex").write_text("% AUTO-GENERATED by 23_supplement_tables.py\n" + "\n".join(lines) + "\n")

    sim = pd.read_csv(RES / "simulation.csv")
    meth = {"single": "Single series", "cits": "Comparative (CITS)", "cits_plac": "CITS + placebo",
            "local24": "Local $\\pm$24", "rcs": "Spline pre-trend"}
    rows = ["\\begin{tabular}{llrrrr}", "\\toprule",
            "Drift & Method & $\\delta=0$ & 0.5 & 1.0 & 1.5 \\\\", "\\midrule"]
    for sc, S in [("no_drift", "0"), ("half_drift", "0.5$\\times$"), ("fitted", "1.0$\\times$")]:
        for mk, mn in meth.items():
            v = [sim[(sim.scenario == sc) & (sim.method == mk) & (sim.effect_sd == d)].reject_rate.iloc[0] * 100
                 for d in [0.0, 0.5, 1.0, 1.5]]
            rows.append(f"{S} & {mn} & " + " & ".join(f"{x:.1f}" for x in v) + " \\\\")
        rows.append("\\midrule" if sc != "fitted" else "\\bottomrule")
    rows.append("\\end{tabular}")
    (OUT / "supp_simtable.tex").write_text("\n".join(rows) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
